### ISSUE TITLE
Tablet prefab fixes and improvements

### ISSUE THREAD

**Issue by fominykh** [vr4vet/vr4vet#239]

**Comment by alxyzz** [comment]
feedback on tablet 
- subtasks and tasks don't update as you fulfill them, it takes some time
- some tablet screens are stuck on the wrong page index for some lists
- laser pointer is rendered below the tablet layer

**Comment by ingolvjr** [comment]
Some text fields are hard-coded to placeholder text

**Comment by fominykh** [comment]
@irtazakhan are you still working on the Tablet? If yes, please, assign yourself. We are collecting things to do under this issue.

**Comment by ottedam** [comment]
New Tablet >Tablet Adapted > Screen_AboutTask >Interactibles was not active
New Tablet >Tablet Adapted > Screen_aboutSubTask > Interactibles > SubTaskMainInfo > panel_TaskAbout > btn_steps missing on click actions
There is always a 1/2 on the subtasks page and I believe as well on the steps page
Backbutton does not seem to work
The pointer only shows when you are pointing at a button that you can press. I believe this can be fixed by removing a component called alpha group or something along those lines
The dot of the pointer does not show on the canvas but on the underside of the tablet
Step completed does not get 1/1 but still 0/1
Tasks don't get their checkmark updated at all
When a task/subtask/step is completed, it should be updated on the tablet

**Comment by qlpham231** [comment]
Tablet UI renders over pointer despite the pointer being in front of the tablet. This can be fixed by changing the "Order in Layer" attribute from 50 to 0 in the Canvas component in the Tablet Adapted object.

**Comment by ottedam** [comment]
Entries per page is only for the task and steps. For subtasks there is not such a thing
