### ISSUE TITLE
Design and concept for the Controller help

### ISSUE THREAD

**Issue by fominykh** [vr4vet/vr4vet#38]
We need define how the controllers will be introduced and explain to the user, including the buttons and functions they have. The design might include, showing a digital twin versions of the correct controller, animations or pointers, voice over introduction, and links to the functions of the buttons (asking the user to teleport when explaining the teleport button).

**Comment by SnorreForbregd** [comment]
Using controller model from Windmill Technician, with small tooltips attached to buttons. Should be dependent on language selected, translations needed.

> English
- Left Joystick
- Right Joystick 
- Left Trigger
- Right Trigger
- Left Grip
- Right Grip
- Move
- Turn
- Teleport
- Activate
- Select
- Grab

> Norwegian
- Venstre Spake
- Høyre Spake
- Venstre Avtrekker
- Høyre Avtrekker
- Venstre Grep
- Høyre Grep
- Bevegelse
- Snu
- Teleportere
- Aktivere
- Velg
- Plukk opp

> Dutch
Translations needed

> German
Translations needed

**Comment by ottedam** [comment]
For the Dutch translations:

- Linker Joystick
- Rechter Joystick
- linker trekker
- Rechter trekker
- Linker greep
- Rechter greep
- Bewegen
- Draaien
- Teleporteren
- Activeren
- Selecteren
- Grijpen

**Comment by SnorreForbregd** [comment]
I am unable to find the controller models and/or prefabs from the Windmill Technician application, and the function to determine which model to use and render it is split across many different scripts, folders, and prefabs. All of these are also quite outdated.

In my opinion it would be better to find the models elsewhere (Most likely the unity asset store), and create a new script to determine which controller model to render. Unless otherwise specified, I will move forward with this plan of action.

**Comment by fominykh** [comment]
Feel free to move forward, @SnorreForbregd . We can use the Windmill as a reference how the final implementation should approximately function.

**Comment by SnorreForbregd** [comment]
Implemented with basic graphics in linked pull request. Creating new issue #183 for improving graphics of the controller tooltips. Current design can be checked through the Controller Tooltips Manager prefab in the linked pull request.
